### ISSUE TITLE
数据解析结构gson

### ISSUE THREAD

**Issue by 530l** [ShuangtaoJia/RetrofitWithCoroutineDemo#2]
{
code:
message:
data:xxx
}
如果api service 写data的实体不行的吗，要写整个json？

**Comment by ShuangtaoJia** [comment]
> { code: message: data:xxx } 如果api service 写data的实体不行的吗，要写整个json？

@linyingfa 不好意思，没太理解你的问题

**Comment by 530l** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 530l** [comment]
要完整的json模型才可以解析嘛？例如那些code，message后台定义的字段我不需要，只要body的json数据生成bean，去解析可以嘛





------------------ 原始邮件 ------------------
发件人: Shuangtao Jia ***@***.***&gt;
发送时间: 2022年3月24日 20:13
收件人: ShuangtaoJia/RetrofitWithCoroutineDemo ***@***.***&gt;
抄送: 530 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ShuangtaoJia/RetrofitWithCoroutineDemo] 数据解析结构gson (Issue #2)





  
{ code: message: data:xxx } 如果api service 写data的实体不行的吗，要写整个json？
  
@linyingfa 不好意思，没太理解你的问题
